# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pierremore <pierremore@student.42.fr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2014/11/03 18:07:23 by pierremore        #+#    #+#              #
#    Updated: 2016/03/10 17:56:48 by pierremore       ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

DEFAULT   = \033[0m
HIGHLIGHT = \033[1m
UNDERLINE = \033[4m
BLINK     = \033[5m
BLACK     = \033[30m
RED       = \033[31m
GREEN     = \033[32m
YELLOW    = \033[33m
BLUE      = \033[34m
PURPLE    = \033[35m
CYAN      = \033[36m
WHITE     = \033[37m

CC = gcc -Wall -Werror -Wextra
NAME = libft.a
SRC = \
		ft_itoa.c \
		ft_memchr.c \
		ft_putendl_fd.c \
		ft_strcpy.c \
		ft_strmap.c \
		ft_strsplit.c \
		ft_lstadd.c \
		ft_memcmp.c \
		ft_putnbr.c \
		ft_strdel.c \
		ft_strmapi.c \
		ft_strstr.c \
		ft_atoi.c \
		ft_lstdel.c \
		ft_memcpy.c \
		ft_putnbr_fd.c \
		ft_strdup.c \
		ft_strncat.c \
		ft_strsub.c \
		ft_bzero.c \
		ft_lstdelone.c \
		ft_memdel.c \
		ft_putstr.c \
		ft_strequ.c \
		ft_strncmp.c \
		ft_strtrim.c \
		ft_isalnum.c \
		ft_lstiter.c \
		ft_memmove.c \
		ft_putstr_fd.c \
		ft_striter.c \
		ft_strncpy.c \
		ft_tolower.c \
		ft_isalpha.c \
		ft_lstmap.c \
		ft_memset.c \
		ft_strcat.c \
		ft_striteri.c \
		ft_strnequ.c \
		ft_toupper.c \
		ft_isascii.c \
		ft_lstnew.c \
		ft_putchar.c \
		ft_strchr.c \
		ft_strjoin.c \
		ft_strnew.c \
		ft_isdigit.c \
		ft_memalloc.c \
		ft_putchar_fd.c \
		ft_strclr.c \
		ft_strlcat.c \
		ft_strnstr.c \
		ft_isprint.c \
		ft_memccpy.c \
		ft_putendl.c \
		ft_strcmp.c \
		ft_strlen.c \
		ft_strrchr.c \
		ft_freetab.c \
		ft_sqrt.c \
		ft_append.c \
		ft_strjoinwchar.c \
		ft_tablen.c

OBJ = $(SRC:.c=.o)

all: $(NAME)

$(NAME): $(OBJ)
	@echo "${GREEN}LIBRARY COMPILATION OK"
	@ar rc $@ $^
	@ranlib $@
	@echo "${GREEN}LIBRARY OK"

%.o: %.c
	@$(CC) -c $< -I includes/ -o $@

clean:
	@rm -f $(OBJ)

fclean: clean
	@rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
	NAME = libft.a
